// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'app/data/model/entitys/alimento.entity.dart';
import 'app/data/model/entitys/refeicao.entity.dart';
import 'app/data/model/entitys/user.entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5797885550165146912),
    name: 'RefeicaoBox',
    lastPropertyId: const obx_int.IdUid(5, 9081034472993270000),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7515351584323012762),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2907393200199476435),
        name: 'nomeRefeicao',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3986154534264964731),
        name: 'dataRefeicao',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(1, 3399983291488124499),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8033121169720173000),
        name: 'periodoRefeicao',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9081034472993270000),
        name: 'userId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 2960133219658199501),
        relationField: 'user',
        relationTarget: 'UserBox',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'alimentoListaRefeicao',
        srcEntity: 'AlimentoBox',
        srcField: 'refeicao',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 6632429645699339538),
    name: 'AlimentoBox',
    lastPropertyId: const obx_int.IdUid(9, 3041707230301789941),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1598222082013596730),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 452618255795929042),
        name: 'nome',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 15149258006280958),
        name: 'carboidratos',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 334946144332565995),
        name: 'gordura',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4650212959042967173),
        name: 'proteina',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3540989374099819399),
        name: 'caloria',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7168436229398941819),
        name: 'unidadeMedida',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8207456900273264804),
        name: 'valorCota',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3041707230301789941),
        name: 'refeicaoId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 1423389578299902901),
        relationField: 'refeicao',
        relationTarget: 'RefeicaoBox',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 6294384732562797505),
    name: 'UserBox',
    lastPropertyId: const obx_int.IdUid(4, 3897737452820094103),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1801165281259664593),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1841837479110998018),
        name: 'nome',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8620629646789404481),
        name: 'pin',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3897737452820094103),
        name: 'isLoggedIn',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'refeicoes',
        srcEntity: 'RefeicaoBox',
        srcField: 'user',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 6294384732562797505),
    lastIndexId: const obx_int.IdUid(3, 2960133219658199501),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      8628183588665109171,
      2678454613864280679,
      7037542574781544671,
    ],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      1186305008489830881,
      920493422513980867,
      3949236621067748276,
      363041451175972180,
      727308250522707589,
      5500829753680770461,
      4659093685641145474,
      5274561935021005779,
      1390110510755856090,
      8443092945917449618,
      1387472686940961963,
      6026440035012796223,
      3780761263689207011,
      7922628974321057834,
      1680969035779033374,
      6067615415326283364,
      377278787931170997,
      2247946801565594451,
      2017320693549136121,
      3438387466350562578,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    RefeicaoBox: obx_int.EntityDefinition<RefeicaoBox>(
      model: _entities[0],
      toOneRelations: (RefeicaoBox object) => [object.user],
      toManyRelations: (RefeicaoBox object) => {
        obx_int.RelInfo<AlimentoBox>.toOneBacklink(
          9,
          object.id,
          (AlimentoBox srcObject) => srcObject.refeicao,
        ): object.alimentoListaRefeicao,
      },
      getId: (RefeicaoBox object) => object.id,
      setId: (RefeicaoBox object, int id) {
        object.id = id;
      },
      objectToFB: (RefeicaoBox object, fb.Builder fbb) {
        final nomeRefeicaoOffset = fbb.writeString(object.nomeRefeicao);
        final periodoRefeicaoOffset = fbb.writeString(object.periodoRefeicao);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nomeRefeicaoOffset);
        fbb.addInt64(2, object.dataRefeicao?.millisecondsSinceEpoch);
        fbb.addOffset(3, periodoRefeicaoOffset);
        fbb.addInt64(4, object.user.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dataRefeicaoValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final object = RefeicaoBox()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..nomeRefeicao = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..dataRefeicao = dataRefeicaoValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dataRefeicaoValue)
          ..periodoRefeicao = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '');
        object.user.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.user.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<RefeicaoBox>(
          object.alimentoListaRefeicao,
          store,
          obx_int.RelInfo<AlimentoBox>.toOneBacklink(
            9,
            object.id,
            (AlimentoBox srcObject) => srcObject.refeicao,
          ),
        );
        return object;
      },
    ),
    AlimentoBox: obx_int.EntityDefinition<AlimentoBox>(
      model: _entities[1],
      toOneRelations: (AlimentoBox object) => [object.refeicao],
      toManyRelations: (AlimentoBox object) => {},
      getId: (AlimentoBox object) => object.id,
      setId: (AlimentoBox object, int id) {
        object.id = id;
      },
      objectToFB: (AlimentoBox object, fb.Builder fbb) {
        final nomeOffset = fbb.writeString(object.nome);
        final carboidratosOffset = fbb.writeString(object.carboidratos);
        final gorduraOffset = fbb.writeString(object.gordura);
        final proteinaOffset = fbb.writeString(object.proteina);
        final caloriaOffset = fbb.writeString(object.caloria);
        final unidadeMedidaOffset = fbb.writeString(object.unidadeMedida);
        final valorCotaOffset = fbb.writeString(object.valorCota);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nomeOffset);
        fbb.addOffset(2, carboidratosOffset);
        fbb.addOffset(3, gorduraOffset);
        fbb.addOffset(4, proteinaOffset);
        fbb.addOffset(5, caloriaOffset);
        fbb.addOffset(6, unidadeMedidaOffset);
        fbb.addOffset(7, valorCotaOffset);
        fbb.addInt64(8, object.refeicao.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = AlimentoBox()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..nome = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..carboidratos = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..gordura = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..proteina = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..caloria = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..unidadeMedida = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..valorCota = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '');
        object.refeicao.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        object.refeicao.attach(store);
        return object;
      },
    ),
    UserBox: obx_int.EntityDefinition<UserBox>(
      model: _entities[2],
      toOneRelations: (UserBox object) => [],
      toManyRelations: (UserBox object) => {
        obx_int.RelInfo<RefeicaoBox>.toOneBacklink(
          5,
          object.id,
          (RefeicaoBox srcObject) => srcObject.user,
        ): object.refeicoes,
      },
      getId: (UserBox object) => object.id,
      setId: (UserBox object, int id) {
        object.id = id;
      },
      objectToFB: (UserBox object, fb.Builder fbb) {
        final nomeOffset = fbb.writeString(object.nome);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nomeOffset);
        fbb.addInt64(2, object.pin);
        fbb.addBool(3, object.isLoggedIn);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = UserBox()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..nome = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..pin = const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
          ..isLoggedIn = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            10,
            false,
          );
        obx_int.InternalToManyAccess.setRelInfo<UserBox>(
          object.refeicoes,
          store,
          obx_int.RelInfo<RefeicaoBox>.toOneBacklink(
            5,
            object.id,
            (RefeicaoBox srcObject) => srcObject.user,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [RefeicaoBox] entity fields to define ObjectBox queries.
class RefeicaoBox_ {
  /// See [RefeicaoBox.id].
  static final id = obx.QueryIntegerProperty<RefeicaoBox>(
    _entities[0].properties[0],
  );

  /// See [RefeicaoBox.nomeRefeicao].
  static final nomeRefeicao = obx.QueryStringProperty<RefeicaoBox>(
    _entities[0].properties[1],
  );

  /// See [RefeicaoBox.dataRefeicao].
  static final dataRefeicao = obx.QueryDateProperty<RefeicaoBox>(
    _entities[0].properties[2],
  );

  /// See [RefeicaoBox.periodoRefeicao].
  static final periodoRefeicao = obx.QueryStringProperty<RefeicaoBox>(
    _entities[0].properties[3],
  );

  /// See [RefeicaoBox.user].
  static final user = obx.QueryRelationToOne<RefeicaoBox, UserBox>(
    _entities[0].properties[4],
  );

  /// see [RefeicaoBox.alimentoListaRefeicao]
  static final alimentoListaRefeicao =
      obx.QueryBacklinkToMany<AlimentoBox, RefeicaoBox>(AlimentoBox_.refeicao);
}

/// [AlimentoBox] entity fields to define ObjectBox queries.
class AlimentoBox_ {
  /// See [AlimentoBox.id].
  static final id = obx.QueryIntegerProperty<AlimentoBox>(
    _entities[1].properties[0],
  );

  /// See [AlimentoBox.nome].
  static final nome = obx.QueryStringProperty<AlimentoBox>(
    _entities[1].properties[1],
  );

  /// See [AlimentoBox.carboidratos].
  static final carboidratos = obx.QueryStringProperty<AlimentoBox>(
    _entities[1].properties[2],
  );

  /// See [AlimentoBox.gordura].
  static final gordura = obx.QueryStringProperty<AlimentoBox>(
    _entities[1].properties[3],
  );

  /// See [AlimentoBox.proteina].
  static final proteina = obx.QueryStringProperty<AlimentoBox>(
    _entities[1].properties[4],
  );

  /// See [AlimentoBox.caloria].
  static final caloria = obx.QueryStringProperty<AlimentoBox>(
    _entities[1].properties[5],
  );

  /// See [AlimentoBox.unidadeMedida].
  static final unidadeMedida = obx.QueryStringProperty<AlimentoBox>(
    _entities[1].properties[6],
  );

  /// See [AlimentoBox.valorCota].
  static final valorCota = obx.QueryStringProperty<AlimentoBox>(
    _entities[1].properties[7],
  );

  /// See [AlimentoBox.refeicao].
  static final refeicao = obx.QueryRelationToOne<AlimentoBox, RefeicaoBox>(
    _entities[1].properties[8],
  );
}

/// [UserBox] entity fields to define ObjectBox queries.
class UserBox_ {
  /// See [UserBox.id].
  static final id = obx.QueryIntegerProperty<UserBox>(
    _entities[2].properties[0],
  );

  /// See [UserBox.nome].
  static final nome = obx.QueryStringProperty<UserBox>(
    _entities[2].properties[1],
  );

  /// See [UserBox.pin].
  static final pin = obx.QueryIntegerProperty<UserBox>(
    _entities[2].properties[2],
  );

  /// See [UserBox.isLoggedIn].
  static final isLoggedIn = obx.QueryBooleanProperty<UserBox>(
    _entities[2].properties[3],
  );

  /// see [UserBox.refeicoes]
  static final refeicoes = obx.QueryBacklinkToMany<RefeicaoBox, UserBox>(
    RefeicaoBox_.user,
  );
}
