// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'app/model/entitys/alimento.entity.dart';
import 'app/model/entitys/refeicao.entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 7037542574781544671),
    name: 'AlimentoBox',
    lastPropertyId: const obx_int.IdUid(8, 3438387466350562578),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3780761263689207011),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7922628974321057834),
        name: 'nome',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1680969035779033374),
        name: 'carboidratos',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6067615415326283364),
        name: 'gordura',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 377278787931170997),
        name: 'proteina',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2247946801565594451),
        name: 'caloria',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2017320693549136121),
        name: 'unidadeMedida',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3438387466350562578),
        name: 'valorCota',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5797885550165146912),
    name: 'RefeicaoBox',
    lastPropertyId: const obx_int.IdUid(4, 8033121169720173000),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7515351584323012762),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2907393200199476435),
        name: 'nomeRefeicao',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3986154534264964731),
        name: 'dataRefeicao',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8033121169720173000),
        name: 'periodoRefeicao',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 5797885550165146912),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [8628183588665109171, 2678454613864280679],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      1186305008489830881,
      920493422513980867,
      3949236621067748276,
      363041451175972180,
      727308250522707589,
      5500829753680770461,
      4659093685641145474,
      5274561935021005779,
      1390110510755856090,
      8443092945917449618,
      1387472686940961963,
      6026440035012796223,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AlimentoBox: obx_int.EntityDefinition<AlimentoBox>(
      model: _entities[0],
      toOneRelations: (AlimentoBox object) => [],
      toManyRelations: (AlimentoBox object) => {},
      getId: (AlimentoBox object) => object.id,
      setId: (AlimentoBox object, int id) {
        object.id = id;
      },
      objectToFB: (AlimentoBox object, fb.Builder fbb) {
        final nomeOffset = fbb.writeString(object.nome);
        final carboidratosOffset = fbb.writeString(object.carboidratos);
        final gorduraOffset = fbb.writeString(object.gordura);
        final proteinaOffset = fbb.writeString(object.proteina);
        final caloriaOffset = fbb.writeString(object.caloria);
        final unidadeMedidaOffset = fbb.writeString(object.unidadeMedida);
        final valorCotaOffset = fbb.writeString(object.valorCota);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nomeOffset);
        fbb.addOffset(2, carboidratosOffset);
        fbb.addOffset(3, gorduraOffset);
        fbb.addOffset(4, proteinaOffset);
        fbb.addOffset(5, caloriaOffset);
        fbb.addOffset(6, unidadeMedidaOffset);
        fbb.addOffset(7, valorCotaOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = AlimentoBox()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..nome = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..carboidratos = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..gordura = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..proteina = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..caloria = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..unidadeMedida = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..valorCota = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '');

        return object;
      },
    ),
    RefeicaoBox: obx_int.EntityDefinition<RefeicaoBox>(
      model: _entities[1],
      toOneRelations: (RefeicaoBox object) => [],
      toManyRelations: (RefeicaoBox object) => {},
      getId: (RefeicaoBox object) => object.id,
      setId: (RefeicaoBox object, int id) {
        object.id = id;
      },
      objectToFB: (RefeicaoBox object, fb.Builder fbb) {
        final nomeRefeicaoOffset = fbb.writeString(object.nomeRefeicao);
        final periodoRefeicaoOffset = fbb.writeString(object.periodoRefeicao);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nomeRefeicaoOffset);
        fbb.addInt64(2, object.dataRefeicao.millisecondsSinceEpoch);
        fbb.addOffset(3, periodoRefeicaoOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = RefeicaoBox()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..nomeRefeicao = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..dataRefeicao = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
          )
          ..periodoRefeicao = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '');

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AlimentoBox] entity fields to define ObjectBox queries.
class AlimentoBox_ {
  /// See [AlimentoBox.id].
  static final id = obx.QueryIntegerProperty<AlimentoBox>(
    _entities[0].properties[0],
  );

  /// See [AlimentoBox.nome].
  static final nome = obx.QueryStringProperty<AlimentoBox>(
    _entities[0].properties[1],
  );

  /// See [AlimentoBox.carboidratos].
  static final carboidratos = obx.QueryStringProperty<AlimentoBox>(
    _entities[0].properties[2],
  );

  /// See [AlimentoBox.gordura].
  static final gordura = obx.QueryStringProperty<AlimentoBox>(
    _entities[0].properties[3],
  );

  /// See [AlimentoBox.proteina].
  static final proteina = obx.QueryStringProperty<AlimentoBox>(
    _entities[0].properties[4],
  );

  /// See [AlimentoBox.caloria].
  static final caloria = obx.QueryStringProperty<AlimentoBox>(
    _entities[0].properties[5],
  );

  /// See [AlimentoBox.unidadeMedida].
  static final unidadeMedida = obx.QueryStringProperty<AlimentoBox>(
    _entities[0].properties[6],
  );

  /// See [AlimentoBox.valorCota].
  static final valorCota = obx.QueryStringProperty<AlimentoBox>(
    _entities[0].properties[7],
  );
}

/// [RefeicaoBox] entity fields to define ObjectBox queries.
class RefeicaoBox_ {
  /// See [RefeicaoBox.id].
  static final id = obx.QueryIntegerProperty<RefeicaoBox>(
    _entities[1].properties[0],
  );

  /// See [RefeicaoBox.nomeRefeicao].
  static final nomeRefeicao = obx.QueryStringProperty<RefeicaoBox>(
    _entities[1].properties[1],
  );

  /// See [RefeicaoBox.dataRefeicao].
  static final dataRefeicao = obx.QueryDateProperty<RefeicaoBox>(
    _entities[1].properties[2],
  );

  /// See [RefeicaoBox.periodoRefeicao].
  static final periodoRefeicao = obx.QueryStringProperty<RefeicaoBox>(
    _entities[1].properties[3],
  );
}
